### ISSUE TITLE
Support for vector-0.12

### ISSUE THREAD

**Issue by mayeranalytics** [depressed-pho/bitstream#6]
`bitstream` requires [vector-0.10](https://hackage.haskell.org/package/vector-0.10.12.3), which is somewhat outdated. 
Unfortunately the `vector` library underwent some changes, in particular with regards to `Stream`. From what I can tell, the constructor [was](https://hackage.haskell.org/package/vector-0.10.12.3/docs/Data-Vector-Fusion-Stream-Monadic.html)

```Haskell
forall s . Stream (s -> m (Step s a)) s Size
```

and [is now](https://hackage.haskell.org/package/vector-0.12.0.1/docs/Data-Vector-Fusion-Bundle-Monadic.html)

```Haskell
forall s . Stream (s -> m (Step s a)) s
```

Also, the size hints moved from `Data.Vector.Fusion.Stream.Size` to `Data.Vector.Fusion.Bundle.Size`.

I'm not quite sure what's going on here, the changes seemed to have happened when going from 0.11 to 0.12, and the [changelog](https://github.com/haskell/vector/blob/master/changelog) describes this as the 

> New generalized stream fusion framework.

 Maybe this [2013 paper](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/07/haskell-beats-C.pdf) has something to do with it. 

In any case, it seems to me that it is worth supporting vector-0.12.

**Comment by depressed-pho** [comment]
Fixed in 0.3.0.0
